kind: pipeline
type: docker
name: default

steps:
  - name: publish
    image: appleboy/drone-ssh
    settings:
      host: 150.95.109.21
      port: 22
      username: root
      password:
        from_secret: password
      command_timeout: 6m
      script:
        - cd Covid-19-CoreAPI
        - git reset HEAD --hard
        - git pull
        - docker build -t covid-19.coreapi .
        - docker stop covid19
        - docker run --rm --name covid19 -d -p 5000:80 covid-19.coreapi
    when:
      branch:
        - master
      event:
        - push
      status:
        - success

image_pull_secrets:
  - dockerconfigjson